version: '3.8'

services:
  frontend:
    container_name: aeco-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - net-aeco

  backend:
    container_name: aeco-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    privileged: true
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - net-aeco
    
  db:
    container_name: aeco-db
    image: postgres:12.19
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - aeco-db-data:/var/lib/postgresql/data
    networks:
      - net-aeco

volumes:
  aeco-db-data:

networks:
  net-aeco:
    external: true